C2 c 37
mekomsolutions/openmrs-config-c2c pull request #16
Opened 2020-09-15 08:46 UTC by reagan-meant

2020-09-15 08:49 UTC, reagan-meant commented
@Need proof reading some of the concepts in french...

2020-09-21 15:15 UTC, rbuisson requested changes
Made quite some comments on the French translations and few on the English naming too.
Let me know if you want need to discuss it over a call.

2020-09-21 15:15 UTC, rbuisson commented on configuration/concepts/Consultation_prenatale.csv
>  e28bf540-37ab-4ca2-9197-5e94f75668a7,,,"If yes, Multiple pregnancy","Si oui, Grossesse multiple","If yes, Multiple pregnancy","Si oui, Grossesse multiple",,,Misc,N/A,,,,,,,,,,,
Have we already answered this on line 29?

2020-09-21 15:15 UTC, rbuisson commented on configuration/concepts/Consultation_prenatale.csv
>  50e4eb00-968a-456f-824b-cbe320064dcf,,,Pregnancy below 18 years of age / above 36 years of age,Grossesse en bas de 18 ans / en haut de 36 ans,Pregnancy below 18 years of age / above 36 years of age,G
Should we rename to: "Mother below 18 years of age / above 36 years of age"
Or even "Mother younger than 18 or older that 36".
In French:
'Mère âgée de moins de 18 ans ou de plus de 36 ans'

2020-09-21 15:15 UTC, rbuisson commented on configuration/concepts/Consultation_prenatale.csv
> +6ef80ed0-2102-45d3-a188-ad57c16263dc,,,Where the patient plans to give birth,Où la patiente prévoit elle accoucher?,Where the patient plans to give birth,Où la patiente prévoit elle accoucher?,,,Misc
"Où la patiente prévoit-elle d'accoucher?"
That sounds more like a direct question, ie, the label than a concept really.
Should we set something like 'Intended place/location of the delivery' (exact term yet to be found - feel free to improve it) and rather have the label in the form to be "Where the patient plans to give birth?"
In French that'd be "Lieu prévu de l'accouchement"

2020-09-21 15:15 UTC, rbuisson commented on configuration/concepts/Consultation_prenatale.csv
> -df9cc02b-b427-4262-b30a-7b973aef23fc,,,At home,À la maison,At home,À la maison,,,Misc,N/A,,,,,,,,,,,
"A domicile"

2020-09-21 18:09 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +c4b48a7a-7c13-4e7d-89ad-1df68c5c6801,,CIEL:1425,Visit Number,Nombre de visite,Visit number,Nombre de visite,,,Finding,Numeric,,,,FALSE,,,,,,,
Done

2020-09-21 18:09 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +1b6a7d76-755c-4db9-8f05-42fe28fc3175,,CIEL:160601,Number of live births,Nombre de grossesse,Number of live births,Nombre de grossesse,,,Misc,Numeric,,,,FALSE,,,,,,,
Done

2020-09-21 18:09 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +5bab781c-96be-4c32-b75b-d7906ddff555,,,Pregnancy number,Nombre de grossesse,Pregnancy number,Nombre de grossesse,,,Misc,Numeric,,,,FALSE,,,,,,,
Done

2020-09-21 18:09 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +8d83ff2b-3f6f-432a-b0cd-5b4f2f1055fd,,CIEL:118939,Vision problems,Troubles de vision,Vision problems,Troubles de vision,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-21 18:11 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
>  e28bf540-37ab-4ca2-9197-5e94f75668a7,,,"If yes, Multiple pregnancy","Si oui, Grossesse multiple","If yes, Multiple pregnancy","Si oui, Grossesse multiple",,,Misc,N/A,,,,,,,,,,,
It appears the intention is to be able to capture the reason as to why the radiographer thinks it is a risky pregnancy

2020-09-21 18:11 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
>  50e4eb00-968a-456f-824b-cbe320064dcf,,,Pregnancy below 18 years of age / above 36 years of age,Grossesse en bas de 18 ans / en haut de 36 ans,Pregnancy below 18 years of age / above 36 years of age,G
"Mother younger than 18 or older than 36 years" sounds better...
Done

2020-09-21 18:13 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +6ef80ed0-2102-45d3-a188-ad57c16263dc,,,Where the patient plans to give birth,Où la patiente prévoit elle accoucher?,Where the patient plans to give birth,Où la patiente prévoit elle accoucher?,,,Misc
Added "Planned place/location for delivery".....confirm the fr..."eu / lieu prévu pour la livraison"

2020-09-21 18:14 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +dfb79477-ab61-47c4-b308-e1ab09757c18,,CIEL:162595,Vaginal delivery,Vaginal delivery,Vaginal delivery,Vaginal delivery,,,Finding,N/A,,,,,,,,,,,
done

2020-09-22 07:20 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +2a07d3b8-c3d5-4fae-ac89-e0a1dfdd9915,,CIEL:161033,Birth outcome during the last pregnancy,Accochement lors de la dernière grossesse,Birth outcome during the last pregnancy,Accochement lors de la dern
Done

2020-09-22 07:20 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +df9cc02b-b427-4262-b30a-7b973aef23fc,,CIEL:1536,Home,Maison,Home,Maison,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-22 07:20 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +50a37eff-81a3-4cef-a19c-1f85d4e690d6,,CIEL:1596,Date of most recent pregnancy delivery,Date de l'accouchement de la grossesse la plus récent,Date of most recent pregnancy delivery,Date de l'accouchem
Done

2020-09-22 07:20 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
>  e3892a91-1428-4816-8e83-834dcd738723,,,Complications during the most recent delivery,Complications lors de l'accouchement le plus récent ?,Complications during the most recent delivery,Complications
Done

2020-09-22 07:20 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +7bfa7b15-f519-4d5f-b53b-3a408bfbeedb,,CIEL:1789,Pregnancy age in weeks,Âge de la grossesse en semaines,Pregnancy age in weeks,Âge de la grossesse en semaines,,,Misc,Numeric,,,,,,,,,,,
Done

2020-09-22 07:21 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +6ed50023-d807-492f-a203-8ce87a942a52,,CIEL:1427,Date of last period,Date des  dernières règles,Date of last period,Date des  dernières règles,,,Misc,Date,,,,,,,,,,,
Done

2020-09-22 07:21 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +4ba98e11-cb3b-4a22-be4e-bb43f3078683,,CIEL:163750,Uterine contractions,Contractions utérine,Uterine contractions,Contractions utérine,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-22 07:21 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +7f703275-777c-4237-9d07-36c99ea0966c,,CIEL:153551,Abdominal pain,Douleur abdominale,Abdominal pain,Douleur abdominale,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-22 07:21 UTC, reagan-meant commented on configuration/concepts/Consultation_prenatale.csv
> +e90fa130-09cd-4574-936f-91fca52a9324,,CIEL:125198,Swollen feet,Pieds enflés,Swollen feet,Pieds enflés,,,Misc,N/A,,,,,,,,,,,
Done

2020-11-02 10:00 UTC, closed without merging