HSC-24: Added reason for death concepts
mekomsolutions/openmrs-config-c2c pull request #18
Opened 2020-09-18 15:53 UTC by reagan-meant

2020-09-18 16:00 UTC, rbuisson requested changes
See comments.
And let's make another PR to move the file to Haiti.

2020-09-18 16:00 UTC, rbuisson commented on configuration/concepts/reason_for_death.csv
> +6a52ba5b-1e48-4278-b9a3-422e7c58ce58,,,Post operative complications,Complications post opératoires,Post operative complications,Complications post opératoires,,,Misc,N/A,,,,,,,,,,,
"post-operative" and "post-opératoire"

2020-09-21 14:21 UTC, reagan-meant commented
Moved this csv to [Haiti level](https://github.com/mekomsolutions/openmrs-config-haiti/pull/28)

2020-09-21 14:21 UTC, reagan-meant commented on configuration/concepts/reason_for_death.csv
> +6a52ba5b-1e48-4278-b9a3-422e7c58ce58,,,Post operative complications,Complications post opératoires,Post operative complications,Complications post opératoires,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-21 14:21 UTC, reagan-meant commented on configuration/concepts/reason_for_death.csv
> +5bddb65e-238a-4b94-a6bc-4655838e2c0e,,,Complications of pregnancy or childbirth,Complications de la grossesse ou de l’accouchement,Complications of pregnancy or childbirth,Complications de la grosses
Done

2020-09-21 14:21 UTC, reagan-meant commented on configuration/concepts/reason_for_death.csv
> +30e1c728-f008-4dd1-ab34-2c34a00fd3a5,,,Reason For Death,Raison du décès,Reason For Death,Raison du décès,,,Misc,N/A,,,Road accidents;Cerebrovascular accident;Asphyxia;Other trauma;Other;Unknown;Compl
Done

2020-09-21 14:21 UTC, reagan-meant commented on configuration/concepts/reason_for_death.csv
> +f7169739-7134-4050-8b69-6f55448693f6,,,Respiratory disorder,Problèmes respiratoire,Respiratory disorder,Problèmes respiratoire,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-21 14:21 UTC, reagan-meant commented on configuration/concepts/reason_for_death.csv
> +7cc9702d-f367-4367-85f9-72ac4b406c23,,,Endocrinological disorder,Problèmes endocrinologique,Endocrinological disorder,Problèmes endocrinologique,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-21 14:21 UTC, reagan-meant commented on configuration/concepts/reason_for_death.csv
> +540533db-182f-47b9-b912-f961decbd253,,,Hematological disorder,Problèmes hématologique,Hematological disorder,Problèmes hématologique,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-21 14:22 UTC, reagan-meant commented on configuration/concepts/reason_for_death.csv
> +b3c1d5d0-1a77-416e-98ac-af6fe89b603b,,,Genitourinary disorder,Problèmes génito-urinaire,Genitourinary disorder,Problèmes génito-urinaire,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-21 14:22 UTC, reagan-meant commented on configuration/concepts/reason_for_death.csv
> +7e96af55-e5f7-46f7-8024-2ce9cea3022f,,,Orthopedics disorder,Problèmes Orthopédie,Orthopedics disorder,Problèmes Orthopédie,,,Misc,N/A,,,,,,,,,,,
Done

2020-09-21 14:31 UTC, merged