HSC-24: Cleaned up concepts related to past history
mekomsolutions/openmrs-config-c2c pull request #19
Opened 2020-09-21 13:57 UTC by reagan-meant

2020-09-21 13:59 UTC, reagan-meant commented
@rbuisson Need proof reading the concepts in french

2020-09-21 15:27 UTC, rbuisson requested changes
Few 'fr' changes.

2020-09-21 15:27 UTC, rbuisson commented on configuration/concepts/Historique_sante_form.csv
>  2eac972d-9320-4570-b933-1435599d6885,,,Asthma health history,Asthme Historique de santé,Asthma,Asthme,,,Misc,Boolean,,,,,,,,,,,
I am guessing that those are existing diagnosis concepts right? Let's use them then.

2020-09-21 15:27 UTC, rbuisson commented on configuration/concepts/Historique_sante_form.csv
> +c7a45d8f-3032-4499-92d2-5c4e13f1f824,,,Past Admission History,Antécédents d'admission,Past Admission History,Antécédents d'admission,,,ConvSet,N/A,,,Date;Number of Days;Reason;Hospitals,,,,,,,,
"Historique d'hospitalisations"

2020-09-21 15:27 UTC, rbuisson commented on configuration/concepts/Historique_sante_form.csv
>  f891f12b-9947-4cc4-aa97-b6ba47567a58,,,Allergies health history,Allergies Historique de santé,Allergies,Allergies,,,Misc,Text,,,,,,,,,,,
"Allergies"

2020-09-21 15:27 UTC, rbuisson commented on configuration/concepts/Historique_sante_form.csv
>  61ac6631-a248-4dae-bd32-33520d26c04d,,,Tobacco use,Utilisation de tabac,Tobacco use,Utilisation de tabac,,,Misc,Boolean,,,,,,,,,,,
'Consommation de tabac'

2020-09-21 15:27 UTC, rbuisson commented on configuration/concepts/Historique_sante_form.csv
>  16a035ea-acf0-4e54-9c63-ffd126aaa3f7,,,Use of alcohol,Utilisation d'alcool,Use of alcohol,Utilisation d'alcool,,,Misc,Boolean,,,,,,,,,,,
'Consommation d'alcool'

2020-09-21 15:27 UTC, rbuisson commented on configuration/concepts/Historique_sante_form.csv
>  7d2e95f9-1368-4ef9-b65e-224aba05e5d3,,,Drug use,Utilisation de drogues,Drug use,Utilisation de drogues,,,Misc,Boolean,,,,,,,,,,,
'Consommation de drogues'

2020-09-22 07:31 UTC, reagan-meant commented on configuration/concepts/Historique_sante_form.csv
>  2eac972d-9320-4570-b933-1435599d6885,,,Asthma health history,Asthme Historique de santé,Asthma,Asthme,,,Misc,Boolean,,,,,,,,,,,
This was an over-sight...Fixed

2020-09-22 07:31 UTC, reagan-meant commented on configuration/concepts/Historique_sante_form.csv
>  f891f12b-9947-4cc4-aa97-b6ba47567a58,,,Allergies health history,Allergies Historique de santé,Allergies,Allergies,,,Misc,Text,,,,,,,,,,,
Fixed

2020-11-02 10:00 UTC, closed without merging