Add drugs and retire Legacy visit type
mekomsolutions/openmrs-config-c2c pull request #43
Opened 2021-05-03 18:30 UTC by reagan-meant

2021-05-04 11:24 UTC, rbuisson requested changes

2021-05-04 11:24 UTC, rbuisson commented on configuration/visittypes/data_migration_visit_types.csv
> +e4f9bb8e-8ac5-405f-9baf-21dc8de28a73,True,,,
@reagan-meant , could we rather name this visit type as "N/A"?

2021-05-05 08:30 UTC, reagan-meant commented on configuration/visittypes/data_migration_visit_types.csv
> +e4f9bb8e-8ac5-405f-9baf-21dc8de28a73,True,,,
Fixed

2021-05-05 08:38 UTC, rbuisson approved these changes
Thanks 👍🏻  looks good.

2021-05-05 08:39 UTC, merged