C2C-261: Close stale visits 'scheduled task to run every hour by default'
mekomsolutions/openmrs-config-c2c pull request #72
Opened 2024-02-20 06:41 UTC by kazlaw

Link to ticket --> [here](https://mekomsolutions.atlassian.net/browse/C2C-261)

2024-02-20 08:27 UTC, Ruhanga reviewed
LGTM just a little comment below. Have you tested this @kazlaw?

2024-02-20 08:27 UTC, Ruhanga commented on configuration/liquibase/liquibase.xml
> +        <comment> Add Bahmni preferred EMR API scheduler which closes stale visits </comment>
```suggestion
        <comment> Modify Bahmni preferred EMR API scheduler to close stale visits every hour </comment>
```

2024-02-20 09:08 UTC, kazlaw commented on configuration/liquibase/liquibase.xml
> +        <comment> Add Bahmni preferred EMR API scheduler which closes stale visits </comment>
Not yet @Ruhanga , will proceed with the test and let you know

2024-02-20 09:33 UTC, rbuisson reviewed
I don't think this is going to work. Does it?
This change set has already been processed by Bahmni Core, so I don't think it will re-run.
Additionally, because the comment has changed, it's possible that the changeset checksum will change too. Therefore throwing an error message upon processing.

Best would be to simply create a completely new change set, with the `changeSet id="201905101200` set to something new, so that it's processed like any new change.

2024-02-20 09:44 UTC, kazlaw commented
> I don't think this is going to work. Does it? This change set has already been processed by Bahmni Core, so I don't think it will re-run. Additionally, because the comment has changed, it's possible that the changeset checksum will change too. Therefore throwing an error message upon processing.
> 
> Best would be to simply create a completely new change set, with the `changeSet id="201905101200` set to something new, so that it's processed like any new change.

Let me attempt this

2024-02-27 08:55 UTC, Ruhanga reviewed
Have you tried this out @kazlaw?

2024-03-15 16:17 UTC, rbuisson requested changes

2024-03-15 16:17 UTC, rbuisson commented on configuration/liquibase/liquibase.xml
> +                <where>name="repeat_interval"</where>
The where clause will evaluate a field on the record, not the field name itself.
Eg:
```sql
name = "Close Stale Visits Task";
```
or
```sql
uuid = xxx
```

In your case I would suggest to have the where clause to be the same as the `sqlCheck`:
```sql
<where>schedulable_class = "org.openmrs.module.emrapi.adt.CloseStaleVisitsTask" and name = "Close Stale Visits Task"</where>
```

2024-03-18 06:47 UTC, kazlaw commented
![image](https://github.com/mekomsolutions/openmrs-config-c2c/assets/36139599/3157a483-6d05-4869-871e-7a74f32185bb)

@rbuisson , @Ruhanga the changes from this commit [here](https://github.com/mekomsolutions/openmrs-config-c2c/pull/72/commits/33336975a01b30130f4dcd726bbd36bbfc651d11) insert the value as seen above.

2024-03-18 10:43 UTC, rbuisson approved these changes
@kazlaw , I don't think we need to worry about changing any other field. We should be good to go.

2024-03-18 11:14 UTC, kazlaw commented
Noted, thanks @rbuisson

2024-03-18 11:29 UTC, merged