C2C-319: Add Question: Is the child fully vaccinated?
mekomsolutions/openmrs-config-c2c pull request #75
Opened 2024-04-29 17:34 UTC by kazlaw

Link to ticket [here](https://mekomsolutions.atlassian.net/browse/C2C-319)

2024-04-29 17:35 UTC, kazlaw commented
[Screencast from 29-04-24 20:27:06.webm](https://github.com/mekomsolutions/openmrs-config-c2c/assets/36139599/7be7cee6-7053-4bcc-9ae3-2efe0e32731f)

2024-04-30 09:54 UTC, Ruhanga requested changes

2024-04-30 09:54 UTC, Ruhanga commented on configuration/bahmniforms/vaccinations.json
> +                  {
Let's leave such fields untouched. You only want to copy over the `"resources":` section with the necessary translations, not forgetting to update the relevant reference UUIDs.

2024-05-08 11:55 UTC, kazlaw commented on configuration/bahmniforms/vaccinations.json
> +                  {
This has been addressed [here](https://github.com/mekomsolutions/openmrs-config-c2c/pull/75/commits/1af73243f15bfc91c3c9b70df80861628913b0cf)

[Screencast from 08-05-24 14:48:31.webm](https://github.com/mekomsolutions/openmrs-config-c2c/assets/36139599/6df515d5-43b4-4a3e-96fb-29101b40a01a)

Cc: @Ruhanga

2024-05-09 08:04 UTC, Ruhanga commented on configuration/bahmniforms/vaccinations.json
> +          "dateChanged": "2021-09-30T04:41:12.000+0000"
@kazlaw, this shouldn't be apart of the relevant changes in this PR. Could you undo these?

2024-05-10 08:17 UTC, kazlaw commented on configuration/bahmniforms/vaccinations.json
> +          "dateChanged": "2021-09-30T04:41:12.000+0000"
@Ruhanga those changes are a reverting back of some of the changes the Implementer .json file. They were intended,

2024-05-15 10:41 UTC, Ruhanga approved these changes

2024-05-15 11:26 UTC, merged